version: '3.1'

services:
  backend:
    image: "golang:1.17.3-alpine"
    restart: always
    working_dir: /app
    volumes:
      - "../:/app"
    ports:
      - 8080:8080
    command: go run cmd/backend-core/main.go